# (c) 2017 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
# file or any portion thereof may not be reproduced or used in any manner
# whatsoever without the express written permission of KAI OS TECHNOLOGIES
# (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
# LIMITED or its affiliate company and may be registered in some jurisdictions.
# All other trademarks are the property of their respective owners.

image: buildkite/puppeteer:5.2.1

stages:
  - lint
  - coverage

variables:
  FORCE_COLOR: 'true'
  GAIA_DIR: 'gaia'
  CI_UTILS: 'ci-utils'
  CACHE_DIR: '/cache'

before_script:
  - node -v;
  - yarn -v;
  - apt-get update -y && apt-get install git -y;
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  # Run Yarn to install node modules
  - yarn --pure-lockfile


lint:
  stage: lint
  script:
    - yarn app:lint

coverage:
  stage: coverage
  script:
    - yarn --frozen-lockfile --cache-folder .yarn-cache
    - yarn app:test
